common: &common
  adapter: mysql2
  encoding: utf8
  username: root

development: &development
  <<: *common
  database: leave_managment_dev
  password: password
  host: 127.0.0.1

test: &test
  <<: *development
  database: leave_managment_test

cucumber:
  <<: *test